# Generated by Django 2.0.7 on 2018-07-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pizza_id', models.IntegerField()),
                ('pizza_size', models.IntegerField()),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_address', models.CharField(max_length=250)),
            ],
        ),
    ]
