# Generated by Django 2.0.7 on 2018-07-24 13:37

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pizza_size',
            field=models.IntegerField(validators=[api.models.validate_pizza_size]),
        ),
    ]
